import React, { useState } from "react";
import dynamic from "next/dynamic";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ProductPage from "../components/product";
import Modal from "@/components/modal";

const ModalDynamic = dynamic(() => import("@/components/modal"), {
  ssr: false,
});

export default function Home() {
  const [shouldShow, setShouldShow] = useState(false);

  const handleClick = () => {
    setShouldShow(!shouldShow);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <ProductPage />
        {shouldShow && <Modal />}
        <button onClick={handleClick}>Show hide modal</button>
      </main>
    </>
  );
}
